# Generated by Django 3.2.3 on 2022-06-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbvs', '0021_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='fingerprint',
            field=models.CharField(default='null', max_length=16),
            preserve_default=False,
        ),
    ]
