# Generated by Django 3.2.3 on 2022-06-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbvs', '0022_voter_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='noi',
            field=models.CharField(default='null', max_length=16),
            preserve_default=False,
        ),
    ]
