# Generated by Django 3.2.3 on 2022-06-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbvs', '0023_user_noi'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='booth',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
