# Generated by Django 3.2.3 on 2022-06-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbvs', '0024_user_booth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='voteridno',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
    ]
